### ISSUE TITLE
Bug: LDAP Connections not closed

### ISSUE THREAD

**Issue by iovcho** [timeoff-management/timeoff-management-application#376]
Hello. I have issue with my timeoff-management software. I have connection to external LDAP server, but each connection from timeoff software to LDAP server keep established. If I restart nodejs service, the connection will be closed. 

![image](https://user-images.githubusercontent.com/11993248/65767276-1054fe80-e136-11e9-884d-661dc2f39bfd.png)

Somebody can help about this case?
Thanks!

**Comment by mirakrejci** [comment]
I have the same issue. I have to restart nodejs or ldap service to close the connections.

**Comment by vpp** [comment]
Got report that patch above fixed the problem. Closing this issue.
