### ISSUE TITLE
Feature Request: Login with Office 365

### ISSUE THREAD

**Issue by malvarezcastillo** [timeoff-management/timeoff-management-application#432]
Instead of checking against LDAP It'd be nice if there were some integration with 365 for login credentials, that way users won't have to remember multiple passwords for this service.

Are there any plans to integrate this?

**Comment by Arno500** [comment]
I'd add the best would be something like OIDC connection.
It'll make it easily compatible with Office 365, Google, Keycloak, Auth0, Trustelem and others...

**Comment by attilabalazsy** [comment]
That would be fanastic for us as well. We do not use hybrid connection, so have different pws for AD and O365. Currently we have 3 options:
1) Every user will have a 3rd pw
2) They will use their O365 email address and local AD pw (very confusing)
3) They will use their UPN and AD pw (in this case the email notifications will not work as the UPN is not a working email address)

None of these are good :(
