### ISSUE TITLE
database

### ISSUE THREAD

**Issue by tigerbones24** [timeoff-management/timeoff-management-application#459]
Hi,

does anyone know how I can connect to the database and change staff name, I spelt it wrong :-(  

Kind Regards
ET

**Comment by vpp** [comment]
@tigerbones24 as an admin user you should be able to edit any employee's name.

**Comment by tigerbones24** [comment]
> @tigerbones24 as an admin user you should be able to edit any employee's name.

yes, I thought that as well but when you try to save it, it sats user exists already :-(

**Comment by tigerbones24** [comment]
Oh, I have figured it out, if you watch closely when you go into the record your will see that the email field changes from theres to your own email, if you correct the email to the staff's email, it lets you change it, just so your aware it then goes back to the admin email for some reason.

Kind Regards,
Tiger

**Comment by vpp** [comment]
Looks like browser is too smart:)

**Comment by tigerbones24** [comment]
> Looks like browser is too smart:)

oh doaaaaaaaaaaaaaaaaahhhhhhh its my password manager hahaha, I feel silly now
