### ISSUE TITLE
How to use the time off api?

### ISSUE THREAD

**Issue by DanielPuenteG** [timeoff-management/timeoff-management-application#523]
![image](https://user-images.githubusercontent.com/103925816/183578570-0ae7f573-47a9-49eb-ae0a-2fe0f1a21eac.png)

**Comment by Danilop95** [comment]
https://github.com/timeoff-management/timeoff-management-application/issues/468

**Comment by DanielPuenteG** [comment]
@Danilop95

**Comment by mandarynian** [comment]
It is any chance to get some updated informations about the topic?
